on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install compatible Bundler
        run: gem install bundler -v 2.4.22

      - name: Install dependencies
        run: bundle _2.4.22_ install

          
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
